In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import math
df = pd.read_csv("") 
df = df.drop(columns='ID')
sleepIndecat, sleepEf = df[["REM sleep percentage", "Deep sleep percentage", "Light sleep percentage"]], df["Sleep efficiency"] 
sleepIndecat = sleepIndecat.to_numpy()
sleepIndecat = sleepIndecat.reshape(3, -1)
m, n = np.shape(sleepIndecat)
print(n, m)
sigma = [0, 0, 0]
for i in range(n):
    sigma[0] += (sleepIndecat[0][i] - sleepIndecat[0].mean())**2
    sigma[1] += (sleepIndecat[1][i] - sleepIndecat[1].mean())**2
    sigma[2] += (sleepIndecat[2][i] - sleepIndecat[2].mean())**2  
sigma[0], sigma[1], sigma[2] = math.sqrt(sigma[0])/n, math.sqrt(sigma[1])/n, math.sqrt(sigma[2])/n
print(sigma)

452 3
[0.8902591401788507, 0.887093485628866, 0.8782510671300707]


In [20]:
X = [[],[],[]]
for i in range(m):
    for j in range(n):
        X[i].append((sleepIndecat[i][j] - sleepIndecat[i].mean())/math.sqrt(n*sigma[i]**2))
X = np.array(X)
r = np.matmul(X, X.transpose())/n
print(r)



[[ 1.         -0.27299006 -0.28618579]
 [-0.27299006  1.         -0.27947004]
 [-0.28618579 -0.27947004  1.        ]]


In [21]:
hi2 = -(n-1-(1/6)*(2*m+5))*math.log(np.linalg.det(r))
print(hi2)
hi2_table = 7.815
print(hi2>hi2_table)


146.429735786599
True


In [25]:
r_inv = np.linalg.inv(r)
F = []
for i in range(m):
    F.append((r_inv[i][i]-1)*((n-m)/(m-1)))
F = np.array(F)
F_table = 2.6
F>F_table

array([ True,  True,  True])

In [26]:
r_h = []
r_h.append((-r_inv[0][1])/math.sqrt(r_inv[0][0]*r_inv[1][1]))
r_h.append((-r_inv[0][2])/math.sqrt(r_inv[0][0]*r_inv[2][2]))
r_h.append((-r_inv[1][2])/math.sqrt(r_inv[1][1]*r_inv[2][2]))
print(r_h)

[-0.38366552026835327, -0.39242646856944635, -0.3879407684654296]


In [28]:
t_st = []
for i in range(m):
    t_st.append((r_h[i]*math.sqrt(n-m-1))/math.sqrt(1-r_h[i]))
print(t_st)
t_st = np.array(t_st)
t_table = 1.984
t_st>t_table

[-6.903609517677576, -7.039003223880064, -6.969778275626023]


array([False, False, False])