# Вступ

In [1]:
print('Hello')

Hello


In [2]:
'Hello'

'Hello'

In [3]:
3+4

7

In [4]:
3+4
print('test')

test


In [10]:
a = 4
b = 7
c = 3

In [13]:
# comment
a+b+c

20

In [12]:
a = 10

### Додаткові можливості Jupyter

In [ ]:
! echo 'hello, world!'

In [ ]:
! mkdir a

In [ ]:
! rm -r a

# Numpy

In [14]:
import numpy as np

In [15]:
x = [2, 3, 4, 6]
y = np.array(x)

In [16]:
print(type(x), x)
print(type(y), y)

<class 'list'> [2, 3, 4, 6]
<class 'numpy.ndarray'> [2 3 4 6]


In [17]:
print(x[0, 2])

TypeError: list indices must be integers or slices, not tuple

In [18]:
print(y[[0, 2, -1, 0]])

[2 4 6 2]


In [19]:
y>3

array([False, False,  True,  True])

In [20]:
print(y[y>3])

[4 6]


In [21]:
print(x * 5)

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [22]:
print(y * 5)

[10 15 20 30]


In [23]:
matrix = [[1, 2, 4], [3, 1, 0]]
nd_array = np.array(matrix)

In [24]:
matrix[0][1]

2

In [25]:
nd_array

array([[1, 2, 4],
       [3, 1, 0]])

In [26]:
print(np.random.randint(3,10, size=(4,4)))

[[6 9 5 5]
 [5 7 5 8]
 [7 3 8 3]
 [8 7 6 4]]


In [27]:
print(np.random.randn(4, 5))

[[-3.58316586e-01 -9.33611965e-01 -4.82455370e-01 -3.18175647e-01
  -8.58715595e-01]
 [ 4.71053915e-01 -3.51129566e-01  1.09774797e+00 -1.15416834e+00
   5.79763298e-04]
 [ 1.47901837e+00  1.54844334e+00  1.38686065e+00 -1.65529749e+00
   6.19864143e-01]
 [-3.12398915e-01  9.91219883e-01  6.35682607e-01 -9.36893972e-01
  -1.09726663e-01]]


In [29]:
b = np.array([1, 2, 3, 4, 5], dtype=float)

In [30]:
b

array([1., 2., 3., 4., 5.])

In [31]:
print(nd_array.ndim, nd_array.shape)

2 (2, 3)


In [32]:
matrix = [2, 'str']
nd_array = np.array(matrix)

In [34]:
nd_array * 5

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [35]:
a = np.array([1, 2, 3])
b = np.array([6, 5, 4])
k = 2

print('Вектор a:', a)
print('Вектор b:', b)
print('Число k:', k)

Вектор a: [1 2 3]
Вектор b: [6 5 4]
Число k: 2


In [36]:
print(a+b)
print(a-b)
print(a*b)

[7 7 7]
[-5 -3 -1]
[ 6 10 12]


In [37]:
np.sum(a)

6

In [38]:
np.dot(a, b)

28

In [39]:
a @ b 

28

In [40]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
a.shape

(15,)

In [42]:
a.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
A = np.array([[1, 1, 7], [0, 1, 2], [4, 32, 1]])
B = np.array([[2, 0, 9],
              [3, 4, 3],
             [18, 5, 0]])

C = np.array([[1, 2, 4]])

In [56]:
C.shape

(1, 3)

In [47]:
A, B

(array([[ 1,  1,  7],
        [ 0,  1,  2],
        [ 4, 32,  1]]),
 array([[ 2,  0,  9],
        [ 3,  4,  3],
        [18,  5,  0]]))

In [48]:
A * B

array([[  2,   0,  63],
       [  0,   4,   6],
       [ 72, 160,   0]])

In [49]:
np.dot(A, B)

array([[131,  39,  12],
       [ 39,  14,   3],
       [122, 133, 132]])

In [50]:
A @ B

array([[131,  39,  12],
       [ 39,  14,   3],
       [122, 133, 132]])

In [57]:
A.shape, C.shape

((3, 3), (1, 3))

In [58]:
A @ C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [59]:
C.shape, A.shape

((1, 3), (3, 3))

In [60]:
C @ A

array([[ 17, 131,  15]])

In [61]:
(C @ A).shape

(1, 3)

In [62]:
A.shape, C.shape

((3, 3), (1, 3))

In [63]:
C = C.reshape(3,1)
C

array([[1],
       [2],
       [4]])

In [64]:
A @ C

array([[31],
       [10],
       [72]])

In [65]:
B = np.array([[2, 0, 9],
              [3, 4, 3],
             [18, 5, 0]])

In [66]:
B[1,2]

3

In [67]:
B[:,1]

array([0, 4, 5])

In [68]:
B[2,:]

array([18,  5,  0])

In [69]:
B[1:]

array([[ 3,  4,  3],
       [18,  5,  0]])

In [70]:
B<4

array([[ True,  True, False],
       [ True, False,  True],
       [False, False,  True]])

In [71]:
B[B<4]

array([2, 0, 3, 3, 0])

In [72]:
B.T

array([[ 2,  3, 18],
       [ 0,  4,  5],
       [ 9,  3,  0]])

In [73]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [75]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## Задачка 

$\ell_{1}$ норма 
(Мангеттенська)
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ обчислюється за формулою:

$$
 \left\Vert x \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} \right|.
$$

$\ell_{2}$ норма (Евклідова)
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ обчислюється за формулою:

$$
 \left\Vert x \right\Vert_{2} = \sqrt{\sum_{i=1}^n \left( x_{i} \right)^2}.
$$

Скалярний добуток в просторі $\mathbb{R}^{n}$ для двох векторів $x = (x_{1}, \dots, x_{n})$ і $y = (y_{1}, \dots, y_{n})$ визнаається як:

$$
\langle x, y \rangle = \sum_{i=1}^n x_{i} y_{i}.
$$

Кут між векторами обчислюється наступним чином

$$
\langle x, y \rangle = \left| x \right| | y | \cos(\alpha)
\implies \cos(\alpha) = \frac{\langle x, y \rangle}{\left|| x |\right| || y ||},
$$

де $\alpha \in [0, \pi]$ — кут між векторами $x$ і $y$.

Обчисліться кут між векторами $a$ і $b$ за допомогою звичайних методів NumPy для $\ell_{1}$ і $\ell_{2}$ норм

In [76]:
a = np.array([-34,  -4, -40,  39,  25,   6, -44,  12,  -9,  33, -27,  46,  25,
        -9, -27,  34,   2,   0,  -4,  28, -12,  14, -13,  35,  10, -37,
        16, -19, -50, -38])

b = np.array([  2,   5, -49,  41,  15, -35,  -4,  12,  13, -12, -16,  38,  -4,
       -37, -40, -39, -40, -12, -25, -12, -46,  26,  19, -40,  43,  37,
        28,  36,  19,  31])

#### calculate l1 norm

#### calculate l2 norm

In [81]:
l2_a = np.sqrt(np.sum(a**2))
l2_b = np.sqrt(np.sum(b**2))

#### calculate Dot product (скаляний добуток)

In [83]:
dot_prod = a.dot(b)

#### finall calculation

In [84]:
dot_prod/(l2_a*l2_b)

0.05230935433478235

In [85]:
np.arccos(0.05230935433478235)

1.5184630876316592